---
--- Generated by Luanalysis
--- Created by acakic.
--- DateTime: 8.12.20. 13:30
---

-- 5! = 5 * 4 * 3 * 2 * 1 = 120
function factorial(n)
    if (n == 1) then
        return 1
    else
        return n * factorial(n - 1)
    end
end

print(factorial(10))