---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 11/29/20 6:54 PM
---

--------------------------------------------------------
--[[Create a Lua script that initializes a variable with the salary of an employee.
Your script should calculate and display the value of the original salary increased by 15%.]]

salary = 20000

new_salary = salary * 1.15

print("The new salary in task 16 is " .. new_salary)
--------------------------------------------------------
--[[Initialize a variable with any temperature value in Celsius.
Your script should calculate and display the value in Celsius converted to Fahrenheit.
Assuming TC is the temperature in Celsius and TF is the temperature in Fahrenheit, the conversion formula is:
(0°C × 9/5) + 32 = 32°F]]

temp_celsius = 24
temp_fahrenheit = (temp_celsius * 9 / 5) + 32

print("The converted temperature from celsius to Fahrenheit is: "..temp_fahrenheit)
--------------------------------------------------------