---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 7.12.20. 07:06
---

math.randomseed(os.time())

local prince_codes = {
    { Page = 7, Line = 9, Word = 30, Code = "Y" },
    { Page = 3, Line = 20, Word = 13, Code = "O" },
    { Page = 7, Line = 11, Word = 6, Code = "G" },
    { Page = 13, Line = 5, Word = 9, Code = "V" },
    { Page = 2, Line = 13, Word = 28, Code = "S" },
    { Page = 4, Line = 17, Word = 4, Code = "M" },
    { Page = 13, Line = 7, Word = 17, Code = "N" },
    { Page = 9, Line = 17, Word = 4, Code = "W" },
    { Page = 5, Line = 16, Word = 9, Code = "B" },
    { Page = 2, Line = 19, Word = 9, Code = "X" },
    { Page = 13, Line = 5, Word = 29, Code = "Z" },
    { Page = 2, Line = 1, Word = 16, Code = "X" },
    { Page = 7, Line = 4, Word = 9, Code = "A" },
    { Page = 13, Line = 16, Word = 16, Code = "L" },
    { Page = 5, Line = 17, Word = 30, Code = "R" },
    { Page = 1, Line = 5, Word = 25, Code = "L" },
    { Page = 7, Line = 20, Word = 11, Code = "Z" },
    { Page = 4, Line = 19, Word = 19, Code = "U" },
    { Page = 1, Line = 2, Word = 29, Code = "I" },
    { Page = 9, Line = 2, Word = 22, Code = "Z" },
    { Page = 7, Line = 19, Word = 24, Code = "F" },
    { Page = 3, Line = 4, Word = 3, Code = "N" },
    { Page = 11, Line = 12, Word = 19, Code = "T" },
    { Page = 2, Line = 12, Word = 29, Code = "O" },
    { Page = 5, Line = 15, Word = 9, Code = "M" },
    { Page = 4, Line = 20, Word = 16, Code = "O" },
    { Page = 5, Line = 1, Word = 16, Code = "Q" },
    { Page = 10, Line = 6, Word = 25, Code = "U" },
    { Page = 7, Line = 19, Word = 17, Code = "O" },
    { Page = 5, Line = 13, Word = 14, Code = "N" },
    { Page = 3, Line = 9, Word = 10, Code = "L" },
    { Page = 4, Line = 1, Word = 18, Code = "H" },
    { Page = 1, Line = 8, Word = 25, Code = "B" },
    { Page = 12, Line = 14, Word = 18, Code = "M" },
    { Page = 3, Line = 13, Word = 29, Code = 'F' },
    { Page = 13, Line = 17, Word = 9, Code = "N" },
    { Page = 11, Line = 4, Word = 4, Code = "P" },
    { Page = 6, Line = 4, Word = 28, Code = "J" },
    { Page = 7, Line = 15, Word = 3, Code = "J" },
    { Page = 8, Line = 13, Word = 6, Code = "W" }
}

-- Read the page from the user
print("What is the page you are looking for?")
local page = io.read("*n")

-- Read the line from the user
print("What is the line you are looking for?")
local line = io.read("*n")

-- Read the word from the user
print("What is the word you are looking for?")
local word = io.read("*n")

-- Flag variable if we found the code
local found = false

for i, entry in ipairs(prince_codes) do
    --print("Index: "..i..", Entry: "..entry.Page)
    if (entry.Page == page and entry.Line == line and entry.Word == word) then
        print("The code for this combination is: "..entry.Code)
        found = true
    end
end

-- If flag variable is still false, it means we did not find that combination.
if not found then
    print("Sorry no code found for this combination.")
end

--for i = 1, 40 do
--    print("{ Page = "..math.random(1, 13)..", Line = "..math.random(1, 20)..", Word = "..math.random(1, 30)..", Code = "..string.char(math.random(65, 90)).." },")
--end