---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 11/30/20 7:28 PM
---

menu_option = 3

-- value1 == value2 - equal
-- value1 ~= value2 - different

if menu_option == 1 then
    menu_text = "Can I play, Dad?"
elseif menu_option == 2 then
    menu_text = "Don't hurt me."
elseif menu_option == 3 then
    menu_text = "What the fuck is wrong with this guy?"
elseif menu_option == 4 then
    menu_text = "I am death incarnate!"
end

print("Menu option is: " .. menu_text)