---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 11/30/20 8:14 PM
---
--------------------------------------------------------
--[[
Create a Lua script that initializes a variable with the age of the user. The program should display a message saying if
the user is legally allowed to vote and/or drink according to the current laws of Brazil. A person needs to be at least
16 years old to vote in Brazil, and at least 18 years old to drink.
]]
user_age = 18
if user_age >= 16 then
    print("User is allowed to vote in Brazil!")
elseif user_age >= 18 then
    print("User is allowed to drink as well!")
end
--------------------------------------------------------

--[[
 Create a script that initializes a variable with the current salary of an employee and another variable with how many
 years that employee works at the company. The program should calculate and display the bonus that the employee is
 entitled to get. The bonus is calculated based on a percentage of the employee’s salary, and the percentage depends
 on how long the employee works at the company. If an employee works more than 5 years for the company,
 the bonus is 10% of the salary. If the employee works less than 5 years, the bonus is 7% of the salary.
]]

current_salary = 800
experience_years = 4

if experience_years >= 5 then
    bonus = current_salary * 1.10
else
    bonus = current_salary * 1.07
end

print("Employee's current bonus is: "..bonus)
--------------------------------------------------------