---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 11/30/20 7:46 PM
---

----------------------------------------
-- Exercise:
----------------------------------------
-- Display the correct name of the
-- attack "move" based on the name of
-- the game character.
----------------------------------------
-- Name: Ryu     -> Hadouken
-- Name: Chun Li -> Lightning kick
-- Name: Guile   -> Sonic boom
-- Name: Honda   -> Hundred Hand Slap
-- Name: Ken     -> Hadouken
-- Name: Blanka  -> Electric shock
----------------------------------------

fighter_name = "Ken"

----------------------------------------
-- Select the correct attack move
----------------------------------------
if string.lower(fighter_name) == "Ryu" or
        string.lower(fighter_name) == "Ken" then
    attack_move = "Hadouken"
elseif string.lower(fighter_name) == "Chun Li" then
    attack_move = "Lightning kick"
elseif string.lower(fighter_name) == "Guile" then
    attack_move = "Sonic boom"
elseif string.lower(fighter_name) == "Honda" then
    attack_move = "Hundred Hand Slap"
elseif string.lower(fighter_name) == "Blanka" then
    attack_move = "Electric shock"
end

print(attack_move .. " WHAT ATTACK " .. fighter_name)

