---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 12/4/20 7:45 PM
---

local sum_scores = 0
local num_scores = 0

repeat
    print("Enter a number (0 to exit)")
    local score = io.read("*n")

    if score ~= 0 then
        sum_scores = sum_scores + score
        num_scores = num_scores + 1
    end
until score == 0

local avg = (sum_scores / num_scores)

print("Average num: " .. avg)