---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 12/4/20 8:28 PM
---

--[[
Create a simple Lua function that receives five parameters and returns the result of the average of these five values.]]
function avg_params(a, s, d, f, g)
    return (a + s + d + f + g) / 5
end

--[[Create a Lua function called student_passed() that also receives five parameters representing the five marks scored by a student in a quiz. The function should calculate the overall average of all marks and return true if the student passed (average greater or equal to 70) or false if the student failed (average less than 70).]]
function student_passed()
    local grades = avg_params(100, 98, 53, 92, 88)

    if grades > 70 then
        return true
    else
        return false
    end
end
--------------------------------------------
print("Task 1: " .. avg_params(5, 4, 7, 1, 3))

if student_passed() then
    print("passed")
else
    print("he failed")
end

--[[Create a Lua function that returns if a number is inside a given range. The function should receive three parameters. For example, is_value_inside_range(5, 2, 12) should return true, since 5 is between 2 and 12.]]
-- Function that checks if a number is inside a range [start-end]
function is_value_inside_range(num, range_begin, range_end)
    if num >= range_begin and num <= range_end then
        return true
    end
    return false
end

-- Call the function with some values to test if its correct
if is_value_inside_range(5, 2, 12) then
    print("5 is inside the range [2,12]")
else
    print("5 is not inside the range [2,12]")
end

if is_value_inside_range(2, 4, 6) then
    print("2 is inside the range [4,6]")
else
    print("2 is not inside the range [4,6]")
end

--[[Create a simple Lua function that receives a temperature value in Celsius as a parameter and returns the value converted to Fahrenheit. The conversion formula is listed below.]]
-- Function that receives a temperature in Celsius and convert to Fahrenheit
function celsius_to_fahrenheit(temp_c)
    return (9 / 5) * temp_c + 32
end

-- Call the function with some values to test if the results are correct
print("32 converted to Fahrenheit is "..celsius_to_fahrenheit(32))
print("-4 converted to Fahrenheit is "..celsius_to_fahrenheit(-4))
print("25 converted to Fahrenheit is "..celsius_to_fahrenheit(25))

--[[Create a simple Lua function that receives as a parameter the values of two rectangles (x1, y1, width1, height1, x2, y2, width2, height2) and returns true or false if the two rectangles are colliding with each other or not. This simple collision test falls under what we call AABB (axis-align bounding box). Think of what are the conditions that need to be true for us to safely tell that the first rectangle is colliding with the second one.]]
-- Function to test if rectangle 1 is colliding with rectangle 2
function is_colliding(x1, y1, w1, h1, x2, y2, w2, h2)
    if (x2 >= x1 + w1) or
            (x2 + w2 <= x1) or
            (y2 >= y1 + h1) or
            (y2 + h2 <= y1)
    then
        return false
    else
        return true
    end
end

-- Call the function with some values to test
if is_colliding(10, 10, 20, 8, 12, 13, 20, 6) then
    print("Rectangles are colliding.")
else
    print("Rectangles are not colliding.")
end


