---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 12/4/20 5:42 PM
---

math.randomseed(os.time())

-- Declaring player and enemy positions
local player_x, player_y = 400, 300
local enemy_x, enemy_y = 0, 0

local user_option = 0

-- Loop while user option is different than 4
while user_option ~= 4 do
    -- display a menu on the console
    print("|------------------------------------------------|")
    print("| WELCOME, "..os.date())
    print("|------------------------------------------------|")
    print("| 1. Generate random enemy position.")
    print("| 2. Distance from enemy to player.")
    print("| 3. Get angle from enemy to player.")
    print("| 4. Exit.")
    print("|------------------------------------------------|")

    -- read user input
    print("Please enter your option: ")
    user_option = io.read("*n")

    if user_option == 1 then
        enemy_x = math.random(0, 800)
        enemy_y = math.random(0, 600)

        print("         | - - - - New enemy position: " ..enemy_x.. ", " ..enemy_y.. ")")
    end

    if user_option == 2 then
        local distance = math.sqrt((enemy_x - player_x)^2 + (enemy_y - player_y)^2)
        print("Distance from enemy: " .. distance)
    end

    if user_option == 3 then
        local alpha = math.atan2( (enemy_y - player_y), (enemy_x - player_x) )
        local alpha_in_degrees = math.deg(alpha)
        print("The angle between enemy and the player is: " .. alpha_in_degrees)
    end
end