---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 12/4/20 8:13 PM
---

math.randomseed(os.time())

-- Declaring player and enemy positions
local player_x, player_y = 400, 300
local enemy_x, enemy_y = 0, 0

local user_option = 0

function display_menu()
    -- display a menu on the console
    print("|------------------------------------------------|")
    print("| WELCOME, "..os.date())
    print("|------------------------------------------------|")
    print("| 1. Generate random enemy position.")
    print("| 2. Distance from enemy to player.")
    print("| 3. Get angle from enemy to player.")
    print("| 4. Exit.")
    print("|------------------------------------------------|")

end

function get_distance(x1, y1, x2, y2)
    return math.sqrt((x1 - x2)^2 + (y1 - y2)^2)
end

function get_degrees(x1, y1, x2, y2)
    local a = math.atan( (y1 - y2), (x1 - x2) )
    return math.deg(a)
end
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --- -- ---
while user_option ~= 4 do

    display_menu()

    -- read user input
    print("Please enter your option: ")
    user_option = io.read("*n")

    if user_option == 1 then
        enemy_x = math.random(0, 800)
        enemy_y = math.random(0, 600)

        print("         | - - - - New enemy position: " ..enemy_x.. ", " ..enemy_y.. ")")
    end

    if user_option == 2 then
        local distance = get_distance(player_x, player_y, enemy_x, enemy_y)
        print("Distance from enemy: " .. distance)
    end

    if user_option == 3 then
        print("The angle between enemy and the player is: " .. get_degrees(player_x, enemy_x, player_y, enemy_y))
    end
end
