---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 12/1/20 3:49 PM
---

math.randomseed(os.time())

-- set position of the hero
player_x, player_y = 400, 300

-- enemy_x = math.random(0, 800)
-- enemy_y = math.random(0, 600)

num_enemies = 0

while num_enemies < 1000 do
    local enemy_x = math.random(0, 800)
    local enemy_y = math.random(0, 600)

    if (player_x == enemy_x or player_y == enemy_y) then
        -- TODO: Error - enemy cannot be in same position as player
        print("Enemy and player position clashed!")
    else
        print("Enemy "..num_enemies.." :(".. enemy_x..","..enemy_y..")")
        -- We are incrementing the number of enemies
        num_enemies = num_enemies + 1
    end
end

-- print("enemy_x: "..enemy_x)

print("Thank you! Goodbye!")