---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 12/1/20 2:17 AM
---

math.randomseed(os.time())
-------------------------------TASK: 1---------------------------------
-- Create a script in Lua that generates three random values between 0 and 255.
-- Each value represents one component from an RGB color.
-- Google what color is generated when we combine the three random values that Lua picked for (R)ed, (G)reen, and (B)lue.

function generate_random_values()
    rand_value1 = math.random(0, 255)
    rand_value2 = math.random(0, 255)
    rand_value3 = math.random(0, 255)

    print("Color we just generated is: (".. rand_value1.. ", ".. rand_value2.. ", ".. rand_value3.. ")")
end

-------------------------------TASK: 2---------------------------------
-- Create a script that initializes a string value with the email of an user. The program should display if that variable
--contains a valid email. The requirements for the value to be a valid email are:
-------------------------------      ---------------------------------
-- a) The email should contain an “@” character

-- b) The email should contain a “.” character

-- c) The “@” should occur before the “.” character

-- d) The email should not contain any spaces.

function valid_email()
    local user_email = "aleksa@tfzr.rs"

    local at_char = string.find(user_email, "%@")
    local dot_char = string.find(user_email, "%.")
    local space_char = string.find(user_email, " ")

    -- We add a % in front of the character to avoid Lua replacing those characters
    -- with special values.
    -- For example "." is a pattern that represents *all characters*

    if (not space_char) and (at_char and dot_char) then
        if (at_char < dot_char) then -- test if @ comes before .
            print("Valid email!")
        else
            print("Not a valid email!")
        end
    else
        print("Not a valid email! There is no @ sign, no . sign or spaces found!")
    end
end

-------------------------------TASK: 3---------------------------------
-- Create a script in Lua that initializes a variable with the password string value. The program should display if
-- the password is valid. For a password to be valid, the password should not contain spaces and should
-- have at least 6 characters.

function valid_password()
    entered_password = "cyka"

    if (not string.find(entered_password, " ")) and (#entered_password > 6) then
        print("All good! Password is UNHACKABLE!")
    else
        print("Pls make ur password stronger, you suck!")
    end
end

-------------------------------TASK: 4---------------------------------
-- Create a Lua script that initializes a variable with a number between 1 and 6. The script should also generate a
-- random number between 1 and 6 (simulating the roll of a dice). The program should display a message if both numbers
-- are equal or different, meaning that we guessed the random dice roll correctly or not.

function dnd_dice()
    d_100 = math.random(1, 100)
    d_20 = math.random(1, 20)
    d_12 = math.random(1, 12)
    d_10 = math.random(1, 10)
    d_8 = math.random(1, 8)
    d_6 = math.random(1, 6)
    d_4 = math.random(1, 4)

    rolled_d100, rolled_d20, rolled_d12, rolled_d10, rolled_d8, rolled_d6, rolled_d4 = 69, 20, 6, 9, 7, 3, 1

    if (d_100 == rolled_d100 or d_20 == rolled_d20
            or d_12 == rolled_d20 or d_10 == rolled_d10
            or d_8 == rolled_d8 or d_6 == rolled_d6
            or d_4 == rolled_d4) then
        print("WE GUESSED SOMETHING BOIS!!!")
    else
        print("We missed something bois :c")
    end
end

------------------------------- Function calls ---------------------------------

-- function calls
generate_random_values() -- first seed was a sad pinkprle :c
valid_email() -- Tests for valid user_email
valid_password() -- Password tester! :D
dnd_dice() -- Random number generator :c