---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 12/1/20 1:56 AM
---

sea_level = [[
1993-03-15,	1.4
1994-03-15,	2.7
1995-03-15,	5.7
1996-03-15,	11.4
1997-03-15,	16.1
1998-03-15,	21.9
1999-03-15,	22.1
2000-03-15,	25
2001-03-15,	29.6
2002-03-15,	33.3
2003-03-15,	35.4
2004-03-15,	37.6
2005-03-15,	41.4
2006-03-15,	42.9
2007-03-15,	43.2
2008-03-15,	48.6
2010-03-15,	54.9
2009-03-15,	53.5
2011-03-15,	54.6
2012-03-15,	65.4
2013-03-15,	67.9
2014-03-15,	71.3
]]

sea_level = string.gsub(sea_level, ",", "!")
print(sea_level)

-- In lua, string indices start at position 1!
-- #some string returns length of a string/array