---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 12/1/20 2:02 AM
---

-- x = 0
-- y = 0

x, y = 3, 7
x, y = y, x

print("X: "..x..", Y: "..y)
---------------------------------------

print(math.floor(4.543345))
print(math.pi)
print(math.random(100, 200))

