---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acakic.
--- DateTime: 12/1/20 2:11 AM
---

-- Run this in interpreter

-- use a different seed everytime we start a program
math.randomseed(os.time())

-- Get random enemy position
enemy_x = math.random(0, 800)
enemy_y = math.random(0, 600)

-- Display two random values
print("Enemy position: (".. enemy_x.. ", ".. enemy_x..")")